# Generated by Django 5.1.4 on 2025-03-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL-адрес')),
                ('edition', models.PositiveIntegerField(default=0, verbose_name='Издание')),
                ('volume', models.PositiveIntegerField(default=1, verbose_name='Том')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('publication_date', models.DateField(verbose_name='Дата публикации')),
                ('print_run', models.PositiveIntegerField(default=0, verbose_name='Тираж')),
                ('stock', models.PositiveIntegerField(default=8, verbose_name='Количество на суладе')),
                ('available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Скидка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['-created_at'],
            },
        ),
    ]
